import { readFileSync, writeFileSync } from 'node:fs';

const v2 = JSON.parse(readFileSync('docs/v2/relics.json', 'utf8'));

/**
 * Engine-facing fields the v2.0 document does not carry, because it is a design
 * document. Each is a fact about the mechanism, not the rule, and each is
 * carried forward from the v1.3 registry unless the v2.0 rule changed it.
 *
 * `pre_guess_reveal` is NOT among them any more. It existed to feed §6.3's
 * information cap, which §6.2 removes at five slots — so nothing reads it, and
 * a registry field nothing reads is drift with a delay on it (AGENTS.md
 * non-negotiable 5). It went with the cap.
 */
const ENGINE = {
  'RL.07': {
    activation: { timing: 'ANY_TIME_IN_WORD', usesPerWord: 1, cost: { gold: 15 }, input: 'UNTRIED_LETTER' },
  },
  'RL.20': { activation: { timing: 'BEFORE_SUBMIT', usesPerWord: 1, cost: {}, input: null } },
  'RL.21': { activation: { timing: 'BEFORE_FIRST_GUESS', usesPerWord: 1, cost: {}, input: 'WAGER' } },
  'RL.28': {
    activation: { timing: 'ANY_TIME_IN_WORD', usesPerWord: 1, cost: {}, input: null },
    offer_from_act: 3,
  },
};

const CHARACTER_ENGINE = {
  'CH.03': {
    hook: 'onUse',
    activation: { timing: 'ANY_TIME_IN_WORD', usesPerWord: null, cost: { guesses: 1 }, input: null },
    engine_note: 'No use cap: the guess it costs is the cap.',
  },
};

const relics = v2.relics.map((r) => ({
  ...r,
  ...(ENGINE[r.code]?.activation ? { activation: ENGINE[r.code].activation } : {}),
  ...(ENGINE[r.code]?.offer_from_act ? { offer_from_act: ENGINE[r.code].offer_from_act } : {}),
}));

const consumables = [...v2.consumables];

const characters = v2.characters.map((c) => ({ ...c, ...CHARACTER_ENGINE[c.code] }));

const out = {
  $schema_version: v2.$schema_version,
  _notes: {
    ...v2._notes,
    retired:
      'RL.05 Concordance, RL.08 The Fence, RL.10 Metronome, RL.16 Pilgrim, RL.17 The Holdout, ' +
      'RL.18 Wishbone, RL.24 Ledger, RL.25 Insurance, RL.27 Vault. Nine codes, matching ' +
      'MECHANICS.md §12 R-011. RL.08 and RL.17 are obsolete rather than cut on the §6.4 test: ' +
      'both priced the paid reveal ladder, and v2.0 removes it. Codes are not reused.',
    engine_fields:
      'transform_order, activation and offer_from_act describe the MECHANISM, ' +
      'not the rule. They are carried from the v1.3 registry, which MECHANICS.md v2.0 does not ' +
      'restate because it is a design document. Generated by scripts/registry.mjs.',
  },
  archetypes: v2.archetypes,
  rarities: v2.rarities,
  prices: v2.prices,
  relics,
  consumables,
  characters,
};

writeFileSync('relics.json', JSON.stringify(out, null, 2) + '\n');
console.log(`relics ${relics.length}, consumables ${consumables.length}, characters ${characters.length}`);
